### ISSUE TITLE
Pull request creation

### ISSUE THREAD

**Issue by Azaya89** [bokeh/dataviz-fundamentals#16]
**PROBLEM DESCRIPTION**

I am facing challenges with the way my Pull Requests (PRs) are being created.

**ISSUE DETAILS**

Typically, when I create a PR in a new branch, I notice that all the commits from other unmerged PRs in different branches are also included. For instance, PR #14 was intended to include only the specific named commit, but it also contained unmerged commits from my `main`, `intro`, and `bar-plot` branches, which I did not intend to include. This makes the PR look disorganised.

**WHAT I HAVE TRIED**

I have attempted to create a new branch and use `git cherry-pick` to select only the desired commit to push from that branch. However, this approach has not been successful. I have also tried various suggestions found online, but none of them have resolved the issue. The resulting PRs still include other commits not associated with the specific branch.

**WHAT I NEED**

I need a straightforward method to create PRs with only a single commit, even in cases where there may be unmerged commits from other branches.

**Comment by bryevdv** [comment]
@Azaya89 My usual process looks something like this:
```
# make sure the local main is up to date
git checkout main
git pull upstream main

# make a new branch of this latest main branch
git checkout -b feature-branch

# make changes

# commit and push change
git add ...
git commit -m"..."
git push
```

Based on your description, I might suspect that you are not on the main branch, before you check out your new PR branch, does that seem like it might be the case? When you check out a new branch, git will include all the commits on the branch you are *branching from*, so it's important to make sure to be on `main` before running the `git checkout -b` step. 

If that's not the issue, let's hop on a video call soon, since things will be much easier to debug and diagnose with a screen share.

**Comment by Azaya89** [comment]
In the last PR I did (PR #17),  I made sure to checkout the new branch from `main` after updating `main` via `git fetch upstream` and then `git merge upstream/main`. However, the new branch (`patch2`) *still* contained other commits as shown in the PR.

I wouldn't mind a video call at this point. Maybe there's something I'm missing or overlooking.

**Comment by bryevdv** [comment]
> I wouldn't mind a video call at this point. Maybe there's something I'm missing or overlooking.

OK let's set up a time on Slack!
